### ISSUE TITLE
Error unsubscribing from old subscription filter

### ISSUE THREAD

**Issue by vgaltes** [lumigo-io/SAR-Logging#17]
Hi,

I have Epsagon configured in my account, so they automatically create a subscription.

When I try to use your SAR I always get this error:
```
"oldFilterPattner": "?REPORT ?\"Task timed out\" ?\"Process exited before completing\" ?errorMessage ?\"module initialization error:\" ?\"Unable to import module\" ?\"EPSAGON_TRACE:\"",
```

Is that an error on this SAR or is this an error on Epsagon's stuff?

**Comment by theburningmonk** [comment]
That sounds like Epsagon, my SAR doesn't process the log messages themselves, it just subscribes the log groups to the designated function/kinesis.

Can you at least see the name of the log group? Alternatively, from the message it implies a function has timed out, so look in CloudWatch metrics to look for functions with errors AND high (probably flat-lined if the time out has happened consistently) max duration.

**Comment by vgaltes** [comment]
Thanks Yan,

I'm also seeing these errors:
```
    "message": "cannot process existing log group, skipped...",
    "logGroupName": "/aws/lambda/testauthsls-dev-helloWorld",
    "errorName": "InvalidParameterType",
    "errorMessage": "Expected params.logGroupName to be a string",
    "stackTrace": "InvalidParameterType: Expected params.logGroupName to be a string\n    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)\n    at ParamValidator.validateType (/var/task/node_modules/aws-sdk/lib/param_validator.js:232:10)\n    at ParamValidator.validateString (/var/task/node_modules/aws-sdk/lib/param_validator.js:154:32)\n    at ParamValidator.validateScalar (/var/task/node_modules/aws-sdk/lib/param_validator.js:130:21)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:94:21)\n    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:75:14)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)\n    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)\n    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:126:42)\n    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "awsRegion": "eu-west-1",
```

and 

```
"message": "failed to subscribe log group",
    "logGroupName": [
        "/aws/lambda/TestMadrid",
        "/aws/lambda/test1",
        "/aws/lambda/test4",
        "/aws/lambda/testDonostia",
        "/aws/lambda/testauthsls-dev-helloWorld",
        "/aws/lambda/testauthsls-dev-helloWorldSecured"
    ],
    "errorName": "InvalidParameterType",
    "errorMessage": "Expected params.logGroupName to be a string",
    "stackTrace": "InvalidParameterType: Expected params.logGroupName to be a string\n    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)\n    at ParamValidator.validateType (/var/task/node_modules/aws-sdk/lib/param_validator.js:232:10)\n    at ParamValidator.validateString (/var/task/node_modules/aws-sdk/lib/param_validator.js:154:32)\n    at ParamValidator.validateScalar (/var/task/node_modules/aws-sdk/lib/param_validator.js:130:21)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:94:21)\n    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:75:14)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)\n    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)\n    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:126:42)\n    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "awsRegion": "eu-west-1",
```

**Comment by theburningmonk** [comment]
Ah, that's very interesting! That's the same bug that's described in #14 that I haven't been able to replicate.

Can you tell me which version of the SAR do you have deployed? If you only see it execute once then that suggests it's one of the more recent versions where I'm using custom resources to invoke the subscribeExistingGroups function (instead of hourly).

Also, did you deploy it via the AWS console or through SAM/Serverless/CloudFormation? Can I have a look at your configuration if possible?

**Comment by vgaltes** [comment]
I'm using Serverless to deploy my stack:

```
SubscribeToApiGatewayLogs:
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/auto-subscribe-log-group-to-arn
      SemanticVersion: 1.9.2
    Parameters:
      DestinationArn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:xxxxxxxx
      Prefix: "/aws/lambda"
      OverrideManualConfigs: true
```

I removed the stack and recreated it from scratch and then everything looked good, because I didn't have any subscription against Epsagon and the new functions got subscribed to the right thing. But if I add a new function and deploy again, it doesn't get subscribed to anything.

**Comment by theburningmonk** [comment]
Ok, when you add a new function, it might take a few moments for the CloudWatch events to kick it and subscribe the log group, but you shouldn't have to redeploy.

The function that subscribes all existing log groups would only run again if any of your configuration has changed, so redeploying doesn't trigger it. You can trigger the function by hand though, you should be able to find by looking for `subscribeExisting`.

So you're saying that the first you deploy it, it removed the existing Epsagon subscriptions, then errors with something like this:
```
"message": "failed to subscribe log group",
    "logGroupName": [
        "/aws/lambda/TestMadrid",
        "/aws/lambda/test1",
        "/aws/lambda/test4",
        "/aws/lambda/testDonostia",
        "/aws/lambda/testauthsls-dev-helloWorld",
        "/aws/lambda/testauthsls-dev-helloWorldSecured"
    ],
    "errorName": "InvalidParameterType",
    "errorMessage": "Expected params.logGroupName to be a string",
    "stackTrace": "InvalidParameterType: Expected params.logGroupName to be a string\n    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)\n    at ParamValidator.validateType (/var/task/node_modules/aws-sdk/lib/param_validator.js:232:10)\n    at ParamValidator.validateString (/var/task/node_modules/aws-sdk/lib/param_validator.js:154:32)\n    at ParamValidator.validateScalar (/var/task/node_modules/aws-sdk/lib/param_validator.js:130:21)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:94:21)\n    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:75:14)\n    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)\n    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)\n    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:126:42)\n    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
    "awsRegion": "eu-west-1",
```
but then after you removed the stack and redeployed it managed to subscribe the existing log groups (which by now doesn't have the Epsagon subscription)?

**Comment by vgaltes** [comment]
Exactly. I had the log groups with another subscription (looks like is Epsagon), then I deployed a new version of my service with your SAR on it and deleted the subscription but it didn't add the new one. Then, I removed the service (using sls remove) and redeployed it again and then the logs inside the service got subscribed to the right lambda. But, then, I created a new lambda in my service, and (as you say) after a few moments it got subscribed... but to the wrong lambda

![image](https://user-images.githubusercontent.com/862679/67192226-1ebbd080-f3eb-11e9-8287-03ee3b8c00c2.png)

I guess there's a clash there and I can't have both systems at the same time. I'll make another test removing the Epsagon stuff.

**Comment by theburningmonk** [comment]
I see, let me see if I can reproduce the issue.

A separate thing though, this SAR shouldn't be deployed in every project, otherwise it'll interfere with each other. It's supposed to manage the log subscriptions for the entire region. You should have it as part of your platform - https://theburningmonk.com/2019/10/where-serverless-plugin-stops-and-platform-starts/

**Comment by vgaltes** [comment]
Thanks!

Yep, I'm doing a demo and I'm just putting everything together :P

**Comment by theburningmonk** [comment]
Ha, found the problem - https://github.com/lumigo-io/SAR-Logging/blob/master/packages/cloudwatch-logs-auto-subscribe/functions/subscribe.js#L40 

stupid typo on my part 🤦‍♂

**Comment by vgaltes** [comment]
Awesome, thanks!!
