### ISSUE TITLE
nodejs10.x is nearing end of support

### ISSUE THREAD

**Issue by jurriaanpro** [lumigo-io/SAR-Logging#43]
With nodejs10.x nearing it's end of support date, the applications probably need to updated to the latest supported nodejs version runtime.

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

Is it as easy as updating the runtime here
https://github.com/lumigo-io/SAR-Logging/blob/dd394837468c838703aa86797fe4072931749d1f/packages/cloudwatch-logs-auto-set-retention/template.yml#L19

and here
https://github.com/lumigo-io/SAR-Logging/blob/dd394837468c838703aa86797fe4072931749d1f/packages/cloudwatch-logs-auto-subscribe/template.yml#L19

If so, I can put up a PR with these changes.

**Comment by mirstan** [comment]
Hi, any updates on this, or is this a dead project?

**Comment by mirstan** [comment]
We are not getting failures due to these issues.

**Comment by theburningmonk** [comment]
This has been updated in the latest versions of the SARs
