### ISSUE TITLE
nodejs14.x end of support

### ISSUE THREAD

**Issue by Lanayx** [lumigo-io/SAR-Logging#90]
With nodejs14.x nearing it's end of support date, the applications should be updated to the latest supported nodejs version runtime.

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

(same as https://github.com/lumigo-io/SAR-Logging/issues/43)

**Comment by Lanayx** [comment]
@efimk-lu Hi, will you be able to merge the change and update SAR?

**Comment by Lanayx** [comment]
@theburningmonk thank you for merging in the PR, will you be able to update the application in repository?

**Comment by theburningmonk** [comment]
@Lanayx I pushed and deployed it the other day, maybe I need to nudge the version tag

**Comment by Lanayx** [comment]
I think so, right now it still displays the old version
![image](https://github.com/lumigo-io/SAR-Logging/assets/3329606/99e9025f-af1a-4e17-8a6e-64684b9f9ec9)

**Comment by theburningmonk** [comment]
ok, that should be fixed now. It's been a while, I had to bump the semantic version in the SAM template to get SAR to accept my new version

**Comment by Lanayx** [comment]
Thanks! Unfortunately I've just noticed that current SAR depends on another one which is also outdated, could you please update that one and update the reference in this repository

**Comment by theburningmonk** [comment]
Ok, I updated the other SAR, and pushed an update to the SARs in this repo as well. Hopefully that'd do it!

**Comment by Lanayx** [comment]
Thank you, I've verified and good to close the ticket
